# Generated by Django 5.2.14 on 2026-06-05 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('category_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto')], max_length=10, verbose_name='tipo')),
                ('color', models.CharField(blank=True, default='', max_length=7, verbose_name='color')),
                ('is_default', models.BooleanField(default=False, verbose_name='del sistema')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='InstallmentPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='monto total')),
                ('installment_count', models.PositiveSmallIntegerField(verbose_name='cantidad de cuotas')),
                ('amount_per_installment', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='monto por cuota')),
                ('first_installment_date', models.DateField(verbose_name='fecha primera cuota')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_purchases', to='accounts.account', verbose_name='cuenta')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_purchases', to='transactions.category', verbose_name='categoría')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_purchases', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'compra en cuotas',
                'verbose_name_plural': 'compras en cuotas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='monto')),
                ('transaction_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Gasto'), ('transfer_out', 'Transferencia saliente'), ('transfer_in', 'Transferencia entrante')], max_length=15, verbose_name='tipo')),
                ('date', models.DateField(verbose_name='fecha')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='descripción')),
                ('installment_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='número de cuota')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account', verbose_name='cuenta')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.category', verbose_name='categoría')),
                ('installment_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.installmentpurchase', verbose_name='compra en cuotas')),
                ('transfer_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paired_transfer', to='transactions.transaction', verbose_name='par de transferencia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'transacción',
                'verbose_name_plural': 'transacciones',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
