# Generated by Django 5.2.14 on 2026-06-07 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(choices=[('blue', 'Dólar Blue'), ('oficial', 'Dólar Oficial'), ('tarjeta', 'Dólar Tarjeta'), ('custom', 'Manual')], default='blue', max_length=10, verbose_name='tipo')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='cotización')),
                ('effective_date', models.DateField(verbose_name='fecha de vigencia')),
                ('source', models.CharField(choices=[('dolarapi', 'DolarAPI'), ('manual', 'Manual')], default='dolarapi', max_length=10, verbose_name='origen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates', to=settings.AUTH_USER_MODEL, verbose_name='cargada por')),
            ],
            options={
                'verbose_name': 'tipo de cambio',
                'verbose_name_plural': 'tipos de cambio',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['-effective_date', 'rate_type'], name='currency_ex_effecti_1e7827_idx')],
            },
        ),
    ]
