# Generated by Django 5.2.14 on 2026-06-04 04:54

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('account_type', models.CharField(choices=[('cash', 'Efectivo'), ('digital_wallet', 'Billetera digital'), ('bank', 'Banco'), ('savings', 'Ahorro')], max_length=20, verbose_name='tipo de cuenta')),
                ('currency', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense')], max_length=3, verbose_name='moneda')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='saldo inicial')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='propietario')),
            ],
            options={
                'verbose_name': 'cuenta',
                'verbose_name_plural': 'cuentas',
                'ordering': ['-created_at'],
            },
        ),
    ]
