# Generated by Django 5.2.14 on 2026-06-07 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0002_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='monto neto')),
                ('settled_at', models.DateTimeField(auto_now_add=True, verbose_name='saldado')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_as_creditor', to=settings.AUTH_USER_MODEL, verbose_name='acreedor')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_as_debtor', to=settings.AUTH_USER_MODEL, verbose_name='deudor')),
                ('settled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_initiated', to=settings.AUTH_USER_MODEL, verbose_name='saldado por')),
                ('transfer_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_as_in', to='transactions.transaction', verbose_name='transferencia entrante')),
                ('transfer_out', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_as_out', to='transactions.transaction', verbose_name='transferencia saliente')),
            ],
            options={
                'verbose_name': 'saldo de gastos compartidos',
                'verbose_name_plural': 'saldos de gastos compartidos',
                'ordering': ['-settled_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='monto total')),
                ('currency', models.CharField(choices=[('ARS', 'Peso argentino'), ('USD', 'Dólar estadounidense')], max_length=3, verbose_name='moneda')),
                ('date', models.DateField(verbose_name='fecha')),
                ('debtor_amount', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='monto adeudado')),
                ('is_settled', models.BooleanField(default=False, verbose_name='saldado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_expenses', to='accounts.account', verbose_name='cuenta')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_expenses', to='transactions.category', verbose_name='categoría')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_expenses_created', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_expenses_as_debtor', to=settings.AUTH_USER_MODEL, verbose_name='deudor')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_expenses_as_payer', to=settings.AUTH_USER_MODEL, verbose_name='pagador')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shared_expense', to='transactions.transaction', verbose_name='transacción')),
            ],
            options={
                'verbose_name': 'gasto compartido',
                'verbose_name_plural': 'gastos compartidos',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['is_settled', '-date'], name='shared_shar_is_sett_ecdae8_idx')],
            },
        ),
    ]
